service: events-svc

provider:
  name: aws
  runtime: nodejs6.10

functions:
  get:
    handler: events/get.get
    events:
      - http:
          path: events/{id}
          method: get

plugins:
  - serverless-offline